// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZD6Gqlckt9Q8VKRuoqsXlOA48z3ZkN8',
    appId: '1:984165840137:web:5a45d9e0e296ee13500fd8',
    messagingSenderId: '984165840137',
    projectId: 'agrifresh-8491d',
    authDomain: 'agrifresh-8491d.firebaseapp.com',
    storageBucket: 'agrifresh-8491d.appspot.com',
    measurementId: 'G-ZTRGFHSJHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRWcrpXl5OUsaO1rlLWDs4h4Rt23GXr-s',
    appId: '1:984165840137:android:8e395ad7d2cbd329500fd8',
    messagingSenderId: '984165840137',
    projectId: 'agrifresh-8491d',
    storageBucket: 'agrifresh-8491d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl1zwZs8KWXsoWboWuUbZV1mkpPi4Vcqc',
    appId: '1:984165840137:ios:6474e5b49c0b93eb500fd8',
    messagingSenderId: '984165840137',
    projectId: 'agrifresh-8491d',
    storageBucket: 'agrifresh-8491d.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl1zwZs8KWXsoWboWuUbZV1mkpPi4Vcqc',
    appId: '1:984165840137:ios:6474e5b49c0b93eb500fd8',
    messagingSenderId: '984165840137',
    projectId: 'agrifresh-8491d',
    storageBucket: 'agrifresh-8491d.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ZD6Gqlckt9Q8VKRuoqsXlOA48z3ZkN8',
    appId: '1:984165840137:web:2f7a8c4be53554a9500fd8',
    messagingSenderId: '984165840137',
    projectId: 'agrifresh-8491d',
    authDomain: 'agrifresh-8491d.firebaseapp.com',
    storageBucket: 'agrifresh-8491d.appspot.com',
    measurementId: 'G-YP800K55P7',
  );
}
